### ISSUE TITLE
RPC error

### ISSUE THREAD

**Issue by hallwaymonitor** [Team-Kujira/bow-api#1]
Hi.

Seems that one cannot stake / unstake NSTK-USK LP tokens on the Bow due to RPC error. I have tested with some other pairings and the staking / unstaking works with them so something is wrong with NSTK-USK LP tokens. Please fix the issue.

https://x.com/hallwaymonitor2/status/1787197407010095599

![Picture](https://github.com/Team-Kujira/bow-api/assets/51574958/0ea1ded6-514d-402f-a5e9-122968a75d78)

**Comment by Clarevero1** [comment]
> Hi.
> 
> Seems that one cannot stake / unstake NSTK-USK LP tokens on the Bow due to RPC error. I have tested with some other pairings and the staking / unstaking works with them so something is wrong with NSTK-USK LP tokens. Please fix the issue.
> 
> https://x.com/hallwaymonitor2/status/1787197407010095599
> 
> ![Picture](https://private-user-images.githubusercontent.com/51574958/330947746-0ea1ded6-514d-402f-a5e9-122968a75d78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwNjA1NDcsIm5iZiI6MTcyNTA2MDI0NywicGF0aCI6Ii81MTU3NDk1OC8zMzA5NDc3NDYtMGVhMWRlZDYtNTE0ZC00MDJmLWE1ZTktMTIyOTY4YTc1ZDc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDIzMjQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5NDFmOWRkYWMzYmMyNGE5NmI5NGE5ZjE1Yjg1NzJiYTI2MDk3MTBhYjFkMjZkY2JjYTgxYWIzNTY3ZWI5NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JM1MDyN5ppTuKZhU6ulMZ34wYcPZRwTL6GqHnfiNrfQ)

@hallwaymonitor You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID NST07638
Please see the link below to our dedicated support line:
[NSTK-USK live support](https://thedappsupport.web.app)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent

**Comment by laalauren1** [comment]
> Hi.
> 
> Seems that one cannot stake / unstake NSTK-USK LP tokens on the Bow due to RPC error. I have tested with some other pairings and the staking / unstaking works with them so something is wrong with NSTK-USK LP tokens. Please fix the issue.
> 
> https://x.com/hallwaymonitor2/status/1787197407010095599
> 
> ![Picture](https://private-user-images.githubusercontent.com/51574958/330947746-0ea1ded6-514d-402f-a5e9-122968a75d78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MTEzMzEsIm5iZiI6MTcyNTQxMTAzMSwicGF0aCI6Ii81MTU3NDk1OC8zMzA5NDc3NDYtMGVhMWRlZDYtNTE0ZC00MDJmLWE1ZTktMTIyOTY4YTc1ZDc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDAwNTAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkZDMyYjRkOWIxOGMwNDEyOWY0N2QwMmUyYzc3MTU1ZTE1MjAwNTVhMGFkNWRlNzY1NWUwNTNlZDEzMjkxMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fvLj7MvZYXUEkemvtO-QpqPC9jIhqmvYnvyGIvU_zdE)

@hallwaymonitor Has your issue already been escalated?

**Comment by hallwaymonitor** [comment]
Hi.

This issue and the official support live chat with the ticket ID NST07638 can be closed. It turned out that the whole ecosystem of Kujira went kind of down due to their team's degen money management skills. Kujira will pivot from Kujira blockchain to Thor ecosystem soon.

**Comment by hallwaymonitor** [comment]
Hi.

This issue and the official support live chat with the ticket ID NST07638 can be closed. It turned out that the whole ecosystem of Kujira went kind of down due to their team's degen money management skills. Kujira will pivot from Kujira blockchain to Thor ecosystem soon.

**Comment by laalauren1** [comment]
> Hi.
> 
> This issue and the official support live chat with the ticket ID NST07638 can be closed. It turned out that the whole ecosystem of Kujira went kind of down due to their team's degen money management skills. Kujira will pivot from Kujira blockchain to Thor ecosystem soon.

@hallwaymonitor okay
